name: Python Playwright Testi

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Hae koodi
        uses: actions/checkout@v4

      - name: Asenna Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Asenna Playwright ja testityökalut
        run: |
          pip install pytest-playwright
          playwright install chromium

      - name: Aja testit
        run: pytest test_site.py